# footprint: [[-0.20, -0.20], [-0.20, 0.20], [0.20, 0.20], [0.20, -0.20]]
robot_radius: 0.3
obstacle_range: 3.0
raytrace_range: 3.5

resolution: 0.1

robot_base_frame: base_footprint

cost_scaling_factor: 10.0

static:
  map_topic: /map
  # map_topic: /rtabmap/map_assembler/grid_map

obstacles:
  observation_sources: scan

  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true

    inf_is_valid: true

obstacles_c:
   observation_sources: camera

   camera:
     data_type: PointCloud2
     topic: /obstacles_point_cloud
     marking: true
     clearing: true

inflation:
  inflation_radius: 1.0
