global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  rolling_window: false
  track_unknown_space: true
  static_map: true

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.3

  cost_scaling_factor: 3.0

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
