local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 1.0

  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  # resolution: 0.05
  #
  cost_scaling_factor: 3.0

  plugins:
      - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
      - {name: obstacles_c, type: "costmap_2d::ObstacleLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}
